# Generated by Django 2.2.19 on 2021-12-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211207_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='text',
            new_name='title',
        ),
    ]
